version: "3"
services:
  next:
    container_name: "next"
    # Dockerfileをビルド
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      # バインドマウント
      - ./:/workspace
    tty: true
    env_file:
      - .env